# Generated by Django 4.0.3 on 2022-03-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
