# Generated by Django 4.0.3 on 2022-03-25 12:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='post',
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_post',
            field=models.ForeignKey(
                blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='forum.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='Post_created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
