# Generated by Django 4.0.3 on 2022-03-05 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_author', models.CharField(default='anonymous', max_length=30)),
                ('Post_title', models.CharField(max_length=30)),
                ('Post_content', models.CharField(max_length=1000)),
                ('Post_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_user', models.CharField(max_length=10)),
                ('reply_content', models.CharField(max_length=500)),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='forum.post')),
            ],
        ),
    ]
