# Generated by Django 4.0.3 on 2022-04-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_reply_reply_post_alter_reply_reply_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Post_created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
