# Generated by Django 4.0.3 on 2022-03-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_reply_post_reply_reply_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='reply_post',
        ),
    ]
