# Generated by Django 4.0.3 on 2022-04-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_post_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Post_created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
